users/urls.py
from django.urls import path

from users.views import DashboardEmployees, EmployeeCreateView, DashboardCountries, CountryCreateView, \
    CountryUpdateView, CountryDeleteView, EmployeeUpdateView, EmployeeDeleteView, DashboardCities, CityCreateView, \
    CityUpdateView, CityDeleteView, DashboardOrganizations, OrganizationCreateView, OrganizationUpdateView, \
    OrganizationDeleteView, DashboardDepartments, DepartmentCreateView, DepartmentUpdateView, DepartmentDeleteView, \
    DepartmentDetailsView, DepartmentTableSaveSelection, DepartmentFlushTemplateTableSelection

app_name = 'dashboard'

urlpatterns = [
    # Employees
    path('employees/', DashboardEmployees.as_view(), name='employees'),
    path('employee/create/', EmployeeCreateView.as_view(), name='employee_create'),
    path('employee/update/<int:pk>/', EmployeeUpdateView.as_view(), name='employee_update'),
    path('employee/delete/<int:pk>/', EmployeeDeleteView.as_view(), name='employee_delete'),

    # Countries
    path('countries/', DashboardCountries.as_view(), name='countries'),
    path('country/create/', CountryCreateView.as_view(), name='country_create'),
    path('country/update/<int:pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<int:pk>/', CountryDeleteView.as_view(), name='country_delete'),

    # Cities
    path('cities/', DashboardCities.as_view(), name='cities'),
    path('city/create/', CityCreateView.as_view(), name='city_create'),
    path('city/update/<int:pk>/', CityUpdateView.as_view(), name='city_update'),
    path('city/delete/<int:pk>/', CityDeleteView.as_view(), name='city_delete'),

    # Organizations
    path('organizations/', DashboardOrganizations.as_view(), name='organizations'),
    path('organization/create/', OrganizationCreateView.as_view(), name='organization_create'),
    path('organization/update/<int:pk>/', OrganizationUpdateView.as_view(), name='organization_update'),
    path('organization/delete/<int:pk>/', OrganizationDeleteView.as_view(), name='organization_delete'),

    # Departments
    path('departments/', DashboardDepartments.as_view(), name='departments'),
    path('department/create/', DepartmentCreateView.as_view(), name='department_create'),
    path('department/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'),
    path('department/delete/<int:pk>/', DepartmentDeleteView.as_view(), name='department_delete'),
    path('department/details/<int:pk>/', DepartmentDetailsView.as_view(), name='department_details'),
    path('department/<int:pk>/save-employee-selection/',
         DepartmentTableSaveSelection.as_view(), name='department_save_employee_selection'),
    path('department/<int:pk>/flush-employee-selection/',
         DepartmentFlushTemplateTableSelection.as_view(), name='department_flush_employee_selection'),
]

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% load static %}

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

        {% block static_styles %}
            {% include 'blocks/_styles.html' %}
        {% endblock %}

        <title>Staff Manager</title>
    </head>
    <body>
        {% block base_body %}
            <div id="base-container" class="container-fluid">
                <div id="base-row" class="row">
                    {% block sidebar %}
                        {% include 'components/_collapsible_sidebar.html' %}
                    {% endblock %}
                    <div id="base-content" class="col">
                        {% block navbar %}
                            {% include 'components/_navbar.html' %}
                        {% endblock %}
                        {% block content %}
                        {% endblock %}
                        {% block footer %}
                            {% include 'components/_footer.html' %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        {% endblock %}

        {% include 'components/floating_windows/confirm_action.html' with fw_id='confirm_action' %}
        {% include 'floating_windows/windows/default.html' %}

        {% block static_js %}
            {% include 'blocks/_scripts.html' %}
        {% endblock %}
    </body>
</html>

templates/base_content.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    {% block breadcrumbs %}
        <div class="row">
            <div class="col-12">
                {% include 'components/breadcrumbs.html' with action_set=breadcrumbs only %}
            </div>
        </div>
    {% endblock %}
    {% block alerts %}
        <div class="row">
            <div class="col-12">
                {% include 'components/_alerts.html' with messages=messages only %}
            </div>
        </div>
    {% endblock %}
    <div id="content-base-row" class="row">
        <div class="col-12">
            <div class="content-block">
                <div class="row padding-block content-block-header">
                    {% block content_header %}
                        {% block header_title %}
                            <div class="col content-block-title">{{ title }}</div>
                        {% endblock %}
                        {% block header_toolbar %}{% endblock %}
                    {% endblock %}
                </div>
                <div class="content-block-body">
                    {% block content_body %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/landing.html
<!doctype html>
<html lang="en">
    <head>
        {% load static %}
        {% load i18n %}

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

        {% include 'blocks/_styles.html' %}

        <title>MyManager</title>
    </head>
    <body>
        <div id="base-container" class="container-fluid">
            <div id="base-row" class="row">
                <div id="base-content" class="col">
                    <div id="content-base-row" class="row">
                        {% block content %}
                            <div class="col-12 landing-flex-col">
                                {% include 'components/_logo.html' %}
                                <div class="row landing-content-row landing-left-side-main-row">
                                    <div class="landing-center-content">
                                        <div class="landing-title-level-one">
                                            {% blocktrans %}
                                                Manage your company staff with StaffManager!
                                            {% endblocktrans %}
                                        </div>
                                        <div class="landing-title-level-two">
                                            {% blocktrans %}
                                                StaffManager is a Django demo application that shows the basic CRUD
                                                operations using the company's personnel management as an example.
                                            {% endblocktrans %}
                                        </div>
                                        <a href="{% url 'dashboard:employees' %}" class="btn btn-outline-primary">
                                            Try for free
                                        </a>
                                    </div>
                                </div>
                                {% include 'components/_footer.html' %}
                            </div>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        {% include 'blocks/_scripts.html' %}
    </body>
</html>

templates/system.html
{% extends 'landing.html' %}

{% load i18n %}

{% block content %}
    <div class="col-12 landing-flex-col landing-base-auth-col">
        {% include 'components/_logo.html' %}
        <div class="row landing-content-row landing-auth-main-row">
            {% block content_body %}
                <div class="system-message">
                    <div class="system-message-logo">
                        {{ message_icon }}
                    </div>
                    <div class="system-message-content">
                        <div class="system-message-subject">
                            {{ message_subject }}
                        </div>
                        <div class="system-message-text">
                            {{ message_text }}
                            {% if message_link %}
                                <br>
                                {{ message_link }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endblock %}
        </div>
        {% include 'components/_footer.html' %}
    </div>
{% endblock %}