users/urls.py
from django.urls import path

from users.views import DashboardEmployees, EmployeeCreateView, DashboardCountries, CountryCreateView, \
    CountryUpdateView, CountryDeleteView, EmployeeUpdateView, EmployeeDeleteView, DashboardCities, CityCreateView, \
    CityUpdateView, CityDeleteView, DashboardOrganizations, OrganizationCreateView, OrganizationUpdateView, \
    OrganizationDeleteView, DashboardDepartments, DepartmentCreateView, DepartmentUpdateView, DepartmentDeleteView, \
    DepartmentDetailsView, DepartmentTableSaveSelection, DepartmentFlushTemplateTableSelection

app_name = 'dashboard'

urlpatterns = [
    # Employees
    path('employees/', DashboardEmployees.as_view(), name='employees'),
    path('employee/create/', EmployeeCreateView.as_view(), name='employee_create'),
    path('employee/update/<int:pk>/', EmployeeUpdateView.as_view(), name='employee_update'),
    path('employee/delete/<int:pk>/', EmployeeDeleteView.as_view(), name='employee_delete'),

    # Countries
    path('countries/', DashboardCountries.as_view(), name='countries'),
    path('country/create/', CountryCreateView.as_view(), name='country_create'),
    path('country/update/<int:pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<int:pk>/', CountryDeleteView.as_view(), name='country_delete'),

    # Cities
    path('cities/', DashboardCities.as_view(), name='cities'),
    path('city/create/', CityCreateView.as_view(), name='city_create'),
    path('city/update/<int:pk>/', CityUpdateView.as_view(), name='city_update'),
    path('city/delete/<int:pk>/', CityDeleteView.as_view(), name='city_delete'),

    # Organizations
    path('organizations/', DashboardOrganizations.as_view(), name='organizations'),
    path('organization/create/', OrganizationCreateView.as_view(), name='organization_create'),
    path('organization/update/<int:pk>/', OrganizationUpdateView.as_view(), name='organization_update'),
    path('organization/delete/<int:pk>/', OrganizationDeleteView.as_view(), name='organization_delete'),

    # Departments
    path('departments/', DashboardDepartments.as_view(), name='departments'),
    path('department/create/', DepartmentCreateView.as_view(), name='department_create'),
    path('department/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'),
    path('department/delete/<int:pk>/', DepartmentDeleteView.as_view(), name='department_delete'),
    path('department/details/<int:pk>/', DepartmentDetailsView.as_view(), name='department_details'),
    path('department/<int:pk>/save-employee-selection/',
         DepartmentTableSaveSelection.as_view(), name='department_save_employee_selection'),
    path('department/<int:pk>/flush-employee-selection/',
         DepartmentFlushTemplateTableSelection.as_view(), name='department_flush_employee_selection'),
]

utils/urls.py
from django.urls import path

from utils.views import SidebarModeSaveView, CacheTemplateTableItems

app_name = 'utils'

urlpatterns = [
    path('sidebar-mode/save/<sidebar_id>/<state>/', SidebarModeSaveView.as_view(), name='sidebar_mode_save'),
    path('cache-table-item/<key>/<value>/', CacheTemplateTableItems.as_view(), name='cache_table_item')
]

templates/components/_alerts.html
{% if messages %}
    <div class="custom-alert js-alert_block">
        {% for message in messages %}
            <div class="alert-item {{ message.tags }}">
                <div class="alert-block alert-icon">
                    {% if message.tags == 'warning' %}
                        <i class="material-icons">warning</i>
                    {% elif message.tags == 'info' %}
                        <i class="material-icons">report</i>
                    {% elif message.tags == 'danger' %}
                        <i class="material-icons">flash_on</i>
                    {% elif message.tags == 'success' %}
                        <i class="material-icons">check</i>
                    {% else %}
                        <i class="material-icons">warning</i>
                    {% endif %}
                </div>
                <div class="alert-block alert-message alert-dismissible fade show" role="alert">
                   {{ message | safe }}
                </div>
                <div class="alert-block alert-toolbar">
                    <button type="button" class="btn-outline-light custom-btn alert-close-btn js-alert_dismiss_btn">
                        &times;
                    </button>
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/components/_collapsible_sidebar.html
<!-- Sidebar -->

{% load i18n %}

<div id="main_sidebar" class="col collapsible-sidebar"
     data-is-open="{{ sidebar_menu.sidebar_is_open|yesno:'true,false' }}">
    <div class="sidebar-pos-fixed">
        <div class="row sidebar-row sidebar-row-header">
            <div class="col-12 sidebar-col-logo">
                <div class="sidebar-logo center-on-sidebar-close">
                    <img src="/assets/img/logo_img.png" height="22" width="23">
                    <span class="hide-on-sidebar-close">MyManager</span>
                </div>
            </div>
        </div>
        <div class="row sidebar-row sidebar-row-body">
            <div class="col-12 sidebar-col-body">
                {% for action_set in sidebar_menu %}
                    <div class="sidebar-grouper">
                        <div class="grouper-title">
                            <span class="hide-on-sidebar-close">{{ action_set.group_name }}</span>
                        </div>
                        {% for action in action_set %}
                            <div class="sidebar-btn-wrapper">
                                {{ action }}
                            </div>
                        {% endfor%}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row sidebar-row sidebar-row-footer">
            <div class="col-12">
                <div class="sidebar-toolbar">
                    <button type="button" class="sidebar-toolbar-btn"
                            data-sidebar-toggle="main_sidebar"
                            data-url="{% url 'utils:sidebar_mode_save' 'main_sidebar' sidebar_menu.sidebar_is_open|yesno:'false,true' %}">
                        <i class="material-icons hide-on-sidebar-open">keyboard_arrow_right</i>
                        <i class="material-icons hide-on-sidebar-close">keyboard_arrow_left</i>
                        <span class="hide-on-sidebar-close">{% trans 'Collapse' %}</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/_footer.html
<div id="footer-base-row" class="row">
    <div class="col-12 footer-base-col">
        <img src="/assets/img/logo_img.png" height="15" width="16">
        <span class="footer-logo-title">Staff Manager</span>
        <span class="footer-logo-title text-right">© All rights reserved, {% now 'Y' %} </span>
    </div>
</div>

templates/components/_logo.html
<div class="row landing-logo-row">
    <a class="custom-link" href="{% url 'landing' %}">
        <img src="/assets/img/logo_img.png">
        <span>Staff Manager</span>
    </a>
</div>

templates/components/_navbar.html
<!-- Navbar -->

{% load i18n %}

<div id="navbar-base-row" class="row">
    <div class="row navbar-row navbar-row-badge">
        <div class="col dropdown-with-badge-col" data-dropdown-align="right">
            <div class="row info-badge-row" data-toggle="dropdown" aria-expanded="false">
                <div class="col info-badge-col info-badge-col-align">
                    <div class="info-badge">
                        A
                    </div>
                </div>
                <div class="col info-badge-col-description-align">
                    <div class="row info-badge-row-description info-badge-row-align hide-on-sidebar-close">
                        <span>Anonymous</span>
                        <i class="material-icons ">keyboard_arrow_down</i>
                    </div>
                    <div class="row info-badge-row-description info-badge-row-align hide-on-sidebar-close">
                        <span>No E-mail found</span>
                    </div>
                </div>
            </div>
            <div class="dropdown-menu dropdown-menu-right dropdown-with-badge-menu">
                <div class="dropdown-header">
                    <div class="row info-badge-row">
                        <div class="col info-badge-col">
                            <div class="info-badge">
                                A
                            </div>
                        </div>
                        <div class="col">
                            <div class="row info-badge-row-description">
                                <span>Anonymous User</span>
                            </div>
                            <div class="row info-badge-row-description">
                                <span>Greetings</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <a href="{% url 'landing' %}" class="dropdown-item">
                    <i class="material-icons">chevron_right</i>
                    {% trans 'To start page' %}
                </a>
            </div>
        </div>
    </div>
</div>

templates/components/breadcrumbs.html
{% load dev_tools %}

<div class="breadcrumbs-block">
    <div class="breadcrumbs-current-page">{{ action_set.current_crumb_name }}</div>
    <div class="breadcrumbs-chain">
        <i class="material-icons breadcrumbs-start-icon">bookmark</i>
        {% for action in action_set %}
            {{ action|tweak_parameter:'class: breadcrumb-link' }}
            {% if not forloop.last %}
                <i class="material-icons">chevron_right</i>
            {% endif %}
        {% endfor %}
    </div>
</div>

templates/components/generic_template.html
{% extends 'base_content.html' %}

{% load flex_forms %}

{% block header_toolbar %}
    <div class="col content-block-toolbar">
        {% for action in action_set %}
            {{ action }}
        {% endfor %}
    </div>
{% endblock %}

{% block content_body %}
    {% if form %}
        <div class="row">
            <div class="col-12 form-container">
                {% as_flex form %}
            </div>
        </div>
    {% endif %}
    {% if static_fieldset %}
        <div class="row">
            <div class="col-12 form-container">
                {% as_flex static_fieldset %}
            </div>
        </div>
    {% endif %}
    {% if filter %}
        <div class="row">
            <div class="col-12 form-container">
                {{ filter.form.as_flex }}
            </div>
        </div>
    {% endif %}
    {% if table %}
        <div class="row">
            <div class="col-12">
                <div class="perfect-scrollable js-perfect_scrollbar">
                    {{ table.render }}
                    {{ pagination.render }}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}